---

name: release-please

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

env:
  GEM_NAME: "semian-postgres"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ruby
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          prerelease: true
          package-name: ${{ env.GEM_NAME }}
          version-file: "lib/semian/pg/version.rb"
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}
      - name: Build gem
        run: |
          gem build ${{ env.GEM_NAME }}.gemspec -o ${{ env.GEM_NAME }}.gem
        if: ${{ steps.release.outputs.release_created }}
